spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/recipe-service
    username: postgres
    password: LuckyHusky
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true