spring:
  config:
    import: "optional:aws-parameterstore:/foodies-finds/recipe-service/"
  cloud:
    aws:
      region:
        static: us-east-2
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
      format_sql: true
    show-sql: true
