spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/foodiesfinds
    username: joe
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: recipeservice
    show-sql: true